config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("privacy/", TemplateView.as_view(template_name="pages/privacy.html"), name="privacy"),
    path("impressum/", TemplateView.as_view(template_name="pages/impressum.html"), name="impressum"),
    path('tinymce/', include('tinymce.urls')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("relational_tool.users.urls", namespace="users")),
    path("", include("relational_tool.pages.urls", namespace="pages")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

relational_tool/pages/urls.py
from django.urls.conf import path
from django.views.generic.base import TemplateView
from relational_tool.pages.views import PageCreateView, PageDetailView, PageUpdateView, contacts_csv, contacts_view

app_name = 'pages'

urlpatterns = [
    path("create/", PageCreateView.as_view(), name="page_create"),
    path("<uuid:pk>/", PageDetailView.as_view(), name="page_detail"),
    path("<uuid:pk>/update/", PageUpdateView.as_view(), name="page_update"),
    path("<uuid:pk>/share/", PageUpdateView.as_view(), name="page_share"),
    path("contacts/", contacts_view, name="contacts"),
    path("contacts/csv/", contacts_csv, name="contacts_csv"),
    path("success/", TemplateView.as_view(template_name="pages/signup_success.html"), name="success_page"),
]

relational_tool/users/urls.py
from django.urls import path

from relational_tool.users.views import (
    account_update,
    account_delete,
    account_view,
    login_view,
    logout_view,
    signup_view,
)

app_name = "users"
urlpatterns = [
    path("login/", view=login_view, name="account_login"),
    path("account/", view=account_view, name="account"),
    path("account/update/", view=account_update, name="account_update"),
    path("account/delete/", view=account_delete, name="account_delete"),
    path("signup/", view=signup_view, name="account_signup"),
    path("account/logout/", view=logout_view, name="account_logout"),
]

relational_tool/pages/models.py
import uuid
from django.contrib.auth import get_user_model
from django.db import models
from django.urls.base import reverse
from model_utils.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from tinymce.models import HTMLField
from imagefield.fields import ImageField
# Create your models here.


class Page(TimeStampedModel):
    title = models.CharField(max_length=255, verbose_name=_("Titel"))
    image = ImageField(formats={
        'original': ['default'],
        'site': ['default', ('crop', (1200, 720))],
        'og_image': ['default', ('crop', (1200, 630))],
        'twitter': ['default', ('crop', (800, 418))],
        'square': ['default', ('crop', (1200, 1200))],
    },
                       auto_add_fields=True,
                       blank=True,
                       verbose_name=_("Bild"))
    content = HTMLField(verbose_name=_("Inhalt"))

    active = models.BooleanField(default=True,
                                 verbose_name=_("Aktiviert"),
                                 help_text=_("Wenn die Seite aktiviert ist, können Leute sie sehen."))

    is_rtl = models.BooleanField(
        default=False,
        verbose_name=_("RTL"),
        help_text=_("Aktiviere diese Option, falls der Text von rechts nach links geschrieben wird."))

    def plain_content(self):
        return self.content

    def safe_content(self):
        return mark_safe(self.content)

    owner = models.OneToOneField(
        get_user_model(),
        models.CASCADE,
        related_name="page",
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)

    def get_absolute_url(self):
        return reverse('pages:page_detail', args=(self.id, ))

relational_tool/users/models.py
from typing import Iterable, Optional
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import get_language_info, gettext_lazy as _


class User(AbstractUser):
    """Default user for Relational Tool."""

    zip_code = models.CharField(max_length=10, blank=True, verbose_name=_("PLZ"))
    city = models.CharField(max_length=100, blank=True, verbose_name=_("Ort"))
    phone = models.CharField(max_length=30, blank=True, verbose_name=_("Telefon"))
    email = models.EmailField(verbose_name=_("email address"))
    signed_up_through = models.ForeignKey(
        "pages.Page",
        models.SET_NULL,
        blank=True,
        null=True,
        related_name="contacts",
    )
    language = models.CharField(choices=sorted([(lang[0], get_language_info(lang[0])['name_local'])
                                                for lang in settings.LANGUAGES],
                                               key=lambda x: x[1]),
                                default=settings.LANGUAGE_CODE,
                                max_length=30,
                                verbose_name=_("Sprache"))

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

    def save(self,
             force_insert: bool = False,
             force_update: bool = False,
             using: Optional[str] = None,
             update_fields: Optional[Iterable[str]] = None) -> None:
        if self.pk is None:
            from relational_tool.users import tasks
            ret_val = super().save(force_insert=force_insert,
                                   force_update=force_update,
                                   using=using,
                                   update_fields=update_fields)
            tasks.new_user.delay(self.pk)
            return ret_val
        return super().save(force_insert=force_insert,
                            force_update=force_update,
                            using=using,
                            update_fields=update_fields)

    @property
    def organizer_email(self):
        if self.signed_up_through is not None:
            return self.signed_up_through.owner.email
        return ''

relational_tool/users/forms.py
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class AccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'zip_code', 'city', 'phone', 'language']


class AccountDeletionForm(forms.Form):
    confirm = forms.BooleanField(required=True, label=_("Ich möchte meinen Account löschen"))


class LoginForm(forms.Form):
    email = forms.EmailField(label=_("email address"))

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email, is_active=True).first() is None:
            raise ValidationError(_("Kein Benutzer mit dieser E-Mail Adresse."))
        return email


class SignupForm(forms.ModelForm):
    def save(self):
        self.instance.username = self.instance.email
        super().save()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'zip_code', 'city', 'language']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(username=email).exists():
            raise ValidationError(_("Diese E-Mail Adresse wurde bereits registriert"))
        return email


class PageSignupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.page = kwargs.pop('page', None)
        super().__init__(*args, **kwargs)
        for field in self.fields.items():
            field[1].required = True

    def save(self):
        self.instance.username = self.instance.email
        if self.page is not None:
            self.instance.language = self.page.owner.language
            self.instance.signed_up_through = self.page
        super().save()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'zip_code', 'city']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(username=email).exists():
            raise ValidationError(_("Diese E-Mail Adresse wurde bereits registriert"))
        return email


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {"username": {"unique": _("This username has already been taken.")}}

relational_tool/pages/views.py
from relational_tool.users.tasks import send_success_message
from typing import Optional
import csv

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied
from django.db import models
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.query_utils import Q
from django.forms.models import BaseModelForm
from django.http.request import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.translation import gettext as _
from sesame.utils import get_parameters

from relational_tool.pages.models import Page
from relational_tool.users.forms import PageSignupForm
from relational_tool.users.views import get_auth_link

# Create your views here.

User = get_user_model()


class PageCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Page

    fields = ['image', 'title', 'content', 'active', 'is_rtl']

    def test_func(self):
        return not Page.objects.filter(owner=self.request.user).exists()

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect("pages:page_update", pk=self.request.user.page.pk)
        return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.owner = self.request.user
        return super().form_valid(form)


# /page/:id/ => Need to handle post data
class PageDetailView(DetailView):
    model = Page

    def get_queryset(self) -> models.query.QuerySet:
        if self.request.user.is_authenticated:
            return super().get_queryset().filter(Q(owner__is_active=True, active=True) | Q(owner=self.request.user))
        return super().get_queryset().filter(owner__is_active=True, active=True)

    def post(self, request: HttpRequest, *args, **kwargs):
        self.object = self.get_object()
        form = PageSignupForm(request.POST, page=self.object)

        if form.is_valid():
            form.save()
            user = form.instance
            auth_link = get_auth_link(self.request, user, '/create/')
            send_success_message.delay(user.pk, auth_link)

            return render(request, "pages/signup_success.html", {'form': form})

        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = PageSignupForm(page=self.object)
        return context


# /page/:id/update/
class SharePageView(PageDetailView):
    model = Page
    template_name = "pages/page_share.html"


class PageUpdateView(UpdateView, LoginRequiredMixin, UserPassesTestMixin):
    model = Page

    fields = ['image', 'image_ppoi', 'title', 'content', 'active', 'is_rtl']

    def test_func(self) -> Optional[bool]:
        return self.get_object().owner == self.request.user or self.request.user.is_superuser


@login_required
def contacts_view(request):
    page = request.user.page
    contacts = User.objects.filter(signed_up_through=page, is_active=True)

    return render(request, 'pages/contact_list.html', {'contacts': contacts})


@login_required
def contacts_csv(request):
    page = request.user.page
    contacts = User.objects.filter(signed_up_through=page, is_active=True)
    response = HttpResponse(content_type='text/csv', )

    response['Content-Disposition'] = f'attachment; filename="{request.user.username}_contacts.csv"'

    writer = csv.writer(response)
    writer.writerow([
        _("first name"),
        _("last name"),
        _("email address"),
        _("Telefon"),
        _("PLZ"),
    ])
    for contact in contacts:
        writer.writerow([
            contact.first_name,
            contact.last_name,
            contact.email,
            contact.phone,
            contact.zip_code,
        ])

    return response

relational_tool/users/views.py
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse
import uuid

from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http.request import HttpRequest
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from sesame.utils import get_parameters, get_query_string

from relational_tool.users.forms import (
    AccountDeletionForm,
    AccountForm,
    LoginForm,
    SignupForm,
)
from relational_tool.users.tasks import send_auth_link, send_success_message

User = get_user_model()


def get_auth_link(request, user, url):
    sesam_params = get_parameters(user)
    scheme, netloc, path, params, query, fragment = urlparse(url or '')
    path = path or '/'
    next_params = parse_qs(query)
    next_params.update(sesam_params)
    new_query = urlencode(next_params, doseq=True)
    return request.build_absolute_uri(urlunparse((scheme, netloc, path, params, new_query, fragment)))


def login_view(request: HttpRequest):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.filter(email=email, is_active=True).first()
            login_url = get_auth_link(request, user, request.GET.get('next'))
            send_auth_link.delay(email, login_url)
            return render(request, 'users/login_link_sent.html', {'user': user})

    return render(request, 'users/login_view.html', {'form': form})


def signup_view(request):
    form = SignupForm()

    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth_link = get_auth_link(request, user, '/create/')
            send_success_message.delay(user.pk, auth_link)

            return render(request, "pages/signup_success.html", {'form': form})

    return render(request, 'users/signup_view.html', {'form': form})


@login_required
def logout_view(request):
    user = request.user
    logout(request)
    return render(request, "users/logout_success.html", {'user': user})


@login_required
def account_view(request):
    return render(request, 'users/account_view.html')


@login_required
def account_update(request):
    form = AccountForm(instance=request.user)
    if request.method == "POST":
        form = AccountForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('users:account')
    return render(request, 'users/account_update.html', {'form': form})


@login_required
def account_delete(request):

    form = AccountDeletionForm()

    if request.method == "POST":
        form = AccountDeletionForm(request.POST)

        if form.is_valid():
            user = request.user
            logout(request)
            user.is_active = False
            user.username = str(uuid.uuid4())
            user.save()
            return redirect('home')

    return render(request, 'users/account_delete.html', {'form': form})

relational_tool/templates/users/account_delete.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags %}

{% block content %}
<h1>{% block title %}{% trans 'Löschen bestätigen' %}{% endblock %}</h1>
<p>
<form method="post">
  {% csrf_token %}
  {{form|crispy}}
  <a href="{% url 'users:account' %}" class="btn btn-primary">{% trans 'Zurück' %}</a>
  <button type="submit" class="btn btn-danger">{% trans 'Endgültig Löschen' %}</button>
</form>
</p>
{% endblock %}

relational_tool/templates/users/account_update.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<h1>{% block title %}{% trans "Deine Angaben" %}{% endblock %}</h1>
<p>
  <form action="" method="post">
    {% csrf_token %}
  <table class="table">
    <tbody>
      {{form}}
    </tbody>
  </table>
  <a href="{% url 'users:account' %}" class="btn btn-secondary">{% trans 'Zurück' %}</a>
  <button type="submit" class="btn btn-primary">{% trans 'Speichern' %}</button>

  </form>
</p>
{% endblock content %}

relational_tool/templates/users/account_view.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<h1>{% block title %}{% trans "Deine Angaben" %}{% endblock %}</h1>
<p>
  <table class="table">
    <tbody>
      <tr>
        <th>{% trans "Vorname" %}</th>
        <td>{{user.first_name|default:"-"}}</td>
      </tr>
      <tr>
        <th>{% trans "Nachname" %}</th>
        <td>{{user.last_name|default:"-"}}</td>
      </tr>
      <tr>
        <th>{% trans "E-Mail" %}</th>
        <td>{{user.email|default:"-"}}</td>
      </tr>
      <tr>
        <th>{% trans "PLZ" %}</th>
        <td>{{user.zip_code|default:"-"}}</td>
      </tr>
      <tr>
        <th>{% trans "Stadt" %}</th>
        <td>{{user.city|default:"-"}}</td>
      </tr>
      <tr>
        <th>{% trans "Telefon Nr." %}</th>
        <td>{{user.phone|default:"-"}}</td>
      </tr>
      <tr>
        <th>{% trans "Sprache" %}</th>
        <td>{{user.language|default:"-"}}</td>
      </tr>
    </tbody>
  </table>
  <a href="{% url 'users:account_update' %}" class="btn btn-primary">{% trans 'Aktualisieren' %}</a>
  <a href="{% url 'users:account_delete' %}" class="btn btn-link">{% trans 'Profil löschen' %}</a>
</p>
{% endblock content %}

relational_tool/templates/users/login_link_sent.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<p>
  {% blocktrans %}Du erhältst in Kürze einen Link, mit dem du dich anmelden kannst.{% endblocktrans %}
</p>
{% endblock content %}

relational_tool/templates/users/login_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}

{% block content %}

<h1>{% trans 'Anmelden' %}</h1>

<p>{% trans 'Gib deine E-Mail Adresse an, wir schicken dir dann einen Link, mit dem du dich anmelden kannst.' %}</p>
<form class="form-horizontal mb-2" method="post" action="">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">{% trans 'Log in' %}</button>
    </div>
  </div>
</form>
{% url 'users:account_signup' as register_url %}
<p>{% blocktrans %}Noch kein Zugang? <a href="{{register_url}}">Registriere dich jetzt mit deiner E-Mail Adresse</a>.</p>{% endblocktrans %}
{% endblock content %}

relational_tool/templates/users/logout_success.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<p>
  {% blocktrans %}Erfolgreich abgemeldet!{% endblocktrans %}
</p>
{% endblock content %}

relational_tool/templates/users/signup_success.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Vielen Dank!' %}</h1>
{% blocktrans %}
<p>Mit deiner Hilfe kämpfen wir gemeinsam für die <a href="https://99prozent.ch">99 % Initiative</a>.</p>
<p>Möchtest du deine eigene Seite erstellen um deine Freund*innen über die Initiative zu informieren? Dann melde dich mit deiner E-Mail Adresse an und <a href="#">erstelle deine eigene Seite.</a></p>
{% endblocktrans %}
{% endblock %}

relational_tool/templates/users/signup_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}

{% block content %}
<h1>{% trans 'Registrieren' %}</h1>

<form
  class="form-horizontal mb-2"
  method="post"
  action="{% url 'users:account_signup' %}"
>
  {% csrf_token %}
  {{ form | crispy }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% trans 'Absenden' %}
      </button>

      <div class="form-text text-muted">
        {% include 'privacy_note.html' %}
      </div>
    </div>
  </div>
</form>

{% url 'users:account_login' as login_url %}
<p>{% blocktrans %}Bereits registriert? <a href="{{login_url}}">Melde dich mit deiner E-Mail Adresse an</a>.</p>{% endblocktrans %}

{% endblock content %}

relational_tool/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

relational_tool/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}